/**
 * AI & Machine Learning SEO Keywords
 * Comprehensive keyword collection for AI and machine learning tools category
 */

import type { CategoryKeywords } from './types'

export const aiKeywords: CategoryKeywords = {
  category: 'AI & Machine Learning',
  categoryId: 'ai',
  
  primaryKeywords: [
    'AI tools',
    'artificial intelligence',
    'machine learning',
    'AI software',
    'AI platform',
    'ML tools',
    'deep learning',
    'neural networks',
    'AI solutions',
    'machine learning platform',
    'AI automation',
    'intelligent software',
    'AI-powered tools',
    'machine learning software',
    'artificial intelligence platform'
  ],
  
  secondaryKeywords: [
    'natural language processing',
    'NLP tools',
    'computer vision',
    'image recognition',
    'speech recognition',
    'chatbot',
    'conversational AI',
    'predictive analytics',
    'data science',
    'big data analytics',
    'automated machine learning',
    'AutoML',
    'AI model training',
    'model deployment',
    'AI inference',
    'edge AI',
    'AI APIs',
    'machine learning APIs',
    'AI frameworks',
    'neural network tools',
    'reinforcement learning',
    'supervised learning',
    'unsupervised learning',
    'anomaly detection',
    'recommendation systems',
    'sentiment analysis',
    'text analytics',
    'voice AI',
    'AI writing tools',
    'AI content generation',
    'AI image generation'
  ],
  
  longTailKeywords: [
    'best AI tools for business automation',
    'machine learning platforms for developers',
    'AI-powered chatbot solutions for customer service',
    'natural language processing tools for text analysis',
    'computer vision software for image recognition',
    'automated machine learning platforms for beginners',
    'AI content generation tools for marketing',
    'predictive analytics software for business intelligence',
    'voice recognition software for transcription',
    'AI writing assistants for content creation',
    'machine learning model deployment platforms',
    'AI-powered data analysis tools',
    'conversational AI platforms for enterprises',
    'deep learning frameworks for developers',
    'AI image generation tools for designers',
    'sentiment analysis tools for social media monitoring',
    'AI-powered recommendation engines',
    'automated customer support with AI chatbots',
    'machine learning tools for fraud detection',
    'AI-driven personalization platforms',
    'computer vision APIs for mobile apps',
    'neural network training platforms',
    'AI-powered video analysis tools',
    'machine learning for financial services',
    'AI tools for healthcare diagnostics',
    'predictive maintenance with machine learning',
    'AI-powered sales forecasting tools',
    'natural language generation software',
    'AI-assisted code generation tools',
    'machine learning for marketing optimization',
    'what is the best AI search engine',
    'Perplexity AI alternatives for research',
    'conversational AI platforms like ChatGPT',
    'AI-powered answer engines for businesses',
    'best AI search tools for professionals',
    'how to choose AI research assistants',
    'Perplexity vs Google Search comparison',
    'AI fact-checking and source verification tools',
    'real-time AI search and discovery platforms',
    'AI-powered knowledge management systems',
    'conversational search engines for enterprises',
    'AI research tools for content creators'
  ],
  
  brandKeywords: [
    'OpenAI',
    'GPT',
    'ChatGPT',
    'Google AI',
    'TensorFlow',
    'PyTorch',
    'Hugging Face',
    'Microsoft AI',
    'Azure AI',
    'AWS AI',
    'Amazon SageMaker',
    'IBM Watson',
    'Anthropic',
    'Claude',
    'Midjourney',
    'DALL-E',
    'Stable Diffusion',
    'LangChain',
    'Pinecone',
    'Weights & Biases',
    'MLflow',
    'DataRobot',
    'H2O.ai',
    'Databricks',
    'Palantir',
    'Scale AI',
    'Cohere',
    'Replicate',
    'Runway ML',
    'Jasper AI',
    'Copy.ai',
    'Grammarly',
    'Loom AI',
    'Notion AI',
    'GitHub Copilot',
    'Tabnine',
    'DeepL',
    'Synthesia',
    'Perplexity AI',
    'Perplexity',
    'You.com',
    'Bing AI',
    'Google Bard',
    'SearchGPT'
  ],
  
  locationKeywords: [
    'AI tools USA',
    'machine learning software Canada',
    'artificial intelligence platforms Europe',
    'AI solutions UK',
    'ML tools Australia',
    'AI software global',
    'international AI platforms',
    'worldwide machine learning solutions',
    'local AI tools',
    'regional artificial intelligence software'
  ],
  
  subcategories: {
    'nlp-text': {
      name: 'NLP & Text Analysis',
      path: '/ai/nlp',
      keywords: ['natural language processing', 'NLP', 'text analysis', 'text mining', 'language models'],
      longTail: ['natural language processing tools for businesses', 'text analysis software for sentiment analysis', 'NLP APIs for developers'],
      searchVolume: 'high',
      competition: 'medium'
    },
    'computer-vision': {
      name: 'Computer Vision & Image AI',
      path: '/ai/computer-vision',
      keywords: ['computer vision', 'image recognition', 'object detection', 'facial recognition', 'image analysis'],
      longTail: ['computer vision APIs for mobile apps', 'image recognition software for e-commerce', 'object detection tools for security'],
      searchVolume: 'high',
      competition: 'medium'
    },
    'chatbots-conversational': {
      name: 'Chatbots & Conversational AI',
      path: '/ai/chatbots',
      keywords: ['chatbot', 'conversational AI', 'virtual assistant', 'AI chat', 'customer service AI'],
      longTail: ['AI chatbot platforms for customer support', 'conversational AI for e-commerce', 'virtual assistant for business'],
      searchVolume: 'high',
      competition: 'high'
    },
    'content-generation': {
      name: 'AI Content & Writing',
      path: '/ai/content',
      keywords: ['AI writing', 'content generation', 'AI copywriting', 'automated writing', 'text generation'],
      longTail: ['AI writing tools for marketing', 'automated content generation for blogs', 'AI copywriting software for agencies'],
      searchVolume: 'high',
      competition: 'high'
    },
    'image-generation': {
      name: 'AI Image & Art Generation',
      path: '/ai/image-generation',
      keywords: ['AI image generation', 'AI art', 'image synthesis', 'AI graphics', 'generative art'],
      longTail: ['AI image generation tools for designers', 'AI art creation software', 'automated graphic design with AI'],
      searchVolume: 'high',
      competition: 'high'
    },
    'data-science': {
      name: 'Data Science & Analytics',
      path: '/ai/data-science',
      keywords: ['data science', 'predictive analytics', 'data mining', 'statistical analysis', 'business intelligence'],
      longTail: ['data science platforms for businesses', 'predictive analytics tools for sales', 'automated data analysis software'],
      searchVolume: 'high',
      competition: 'medium'
    },
    'automl-platforms': {
      name: 'AutoML & Model Training',
      path: '/ai/automl',
      keywords: ['AutoML', 'automated machine learning', 'model training', 'ML pipeline', 'no-code ML'],
      longTail: ['automated machine learning platforms for non-technical users', 'no-code ML tools for businesses', 'AutoML solutions for startups'],
      searchVolume: 'medium',
      competition: 'medium'
    },
    'voice-speech': {
      name: 'Voice & Speech AI',
      path: '/ai/voice',
      keywords: ['voice AI', 'speech recognition', 'text to speech', 'voice synthesis', 'audio AI'],
      longTail: ['voice recognition software for transcription', 'text-to-speech tools for accessibility', 'voice AI for customer service'],
      searchVolume: 'medium',
      competition: 'medium'
    },
    'recommendation-engines': {
      name: 'Recommendation Systems',
      path: '/ai/recommendations',
      keywords: ['recommendation engine', 'personalization', 'recommendation system', 'AI recommendations', 'collaborative filtering'],
      longTail: ['AI-powered recommendation engines for e-commerce', 'personalization platforms for websites', 'product recommendation software'],
      searchVolume: 'medium',
      competition: 'medium'
    },
    'ai-automation': {
      name: 'AI Automation & Workflows',
      path: '/ai/automation',
      keywords: ['AI automation', 'intelligent automation', 'AI workflows', 'process automation', 'robotic process automation'],
      longTail: ['AI-powered business process automation', 'intelligent workflow automation tools', 'AI for repetitive task automation'],
      searchVolume: 'high',
      competition: 'medium'
    }
  }
}
